# Generated by Django 6.1 on 2026-09-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='contracts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alerte',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alerte',
            name='email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alerte',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
