# Generated by Django 6.1 on 2026-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0002_alerte_contracts_alerte_domain_alerte_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
