import { userAdapter, companyAdapter, jobAdapter, applicationsAdapter, dateLabel } from "./adapters";
export function adminUser(u) {
 const p=u.profil||{}, apps=applicationsAdapter(u.candidatures||[]);
 return {...userAdapter(u),phone:u.telephone,status:u.is_suspended?"suspended":u.is_active?"active":"inactive",lastLogin:dateLabel(u.last_login),location:p.localisation||"",profileCompleted:p.profile_completion||0,suspensionReason:u.suspension_reason,adminHistory:(u.admin_history||[]).map(h=>({title:h.action,action:h.action,description:h.motif,date:dateLabel(h.created_at),author:"Administration",type:"system"})),
 candidateProfile:{title:p.titre_professionnel,education:p.formations?.map(f=>f.degree).join(", "),institution:p.formations?.[0]?.school||"",experienceLevel:p.annees_experience+" ans",skills:p.competences||[],applications:apps.length,activeApplications:apps.filter(a=>!["RETENU","REFUSE","RETIREE"].includes(a.statut)).length,interviews:apps.filter(a=>a.date_entretien).length,documents:u.documents_count||0},
 recruiterProfile:{companyId:u.entreprise?.id,companyName:u.entreprise?.nom,position:"",companyVerified:u.entreprise?.verification_status==="VERIFIED",offers:u.entreprise?.offres_count||0,activeOffers:0,applications:u.entreprise?.candidatures_count||0,interviews:0},
 title:p.titre_professionnel||"",bio:p.bio||"",summary:p.bio||"",skills:p.competences||[],experiences:p.experiences||[],experience:p.experiences||[],education:p.formations||[],languages:p.langues||[],certifications:[],applications:apps,interviews:u.entretiens||[],documents:u.documents||[],activityHistory:[],registrationDate:dateLabel(u.created_at),lastActivity:dateLabel(u.last_login),availability:p.disponibilite||"",profileCompletion:p.profile_completion||0,stats:{applications:apps.length,interviews:apps.filter(a=>a.date_entretien).length,documents:0,cvs:0}
 };
}
export function adminCompany(c) {
 return {...companyAdapter(c),companyName:c.nom||"",legalName:c.nom||"",recruiterName:c.recruteur?.full_name||"",recruiterRole:"",professionalEmail:c.email_professionnel,registrationDate:dateLabel(c.created_at),lastActivity:dateLabel(c.updated_at),status:c.is_suspended?"suspended":"active",verificationStatus:{PENDING:"pending",VERIFIED:"verified",REJECTED:"rejected",SUSPENDED:"suspended"}[c.verification_status]||"incomplete",verificationSubmittedAt:dateLabel(c.verification_requested_at),offersCount:c.offres_count||0,activeOffers:0,applicationsCount:c.candidatures_count||0,interviewsCount:0,offers:[],documents:[c.document_immatriculation?{id:c.id,kind:"immatriculation",url:c.document_immatriculation,name:"Document d’immatriculation",type:"PDF",status:"provided"}:null,c.preuve_activite?{id:c.id,kind:"activite",url:c.preuve_activite,name:"Preuve d’activité",type:"PDF",status:"provided"}:null].filter(Boolean)};
}
export function adminOffer(j) {
 return {...jobAdapter(j),contractType:j.type_contrat_label||j.type_contrat,workMode:j.mode_travail_label,experienceLevel:j.niveau_experience_label,positions:1,company:{id:j.entreprise,name:j.entreprise_nom,legalName:j.entreprise_nom,sector:j.entreprise_secteur,location:j.localisation,website:"",verified:j.entreprise_verifiee},recruiter:{id:j.recruteur,name:j.recruteur_nom||"",role:"",email:j.recruteur_email||"",phone:""},responsibilities:(j.missions||"").split("\n").filter(Boolean),moderationHistory:[],interviews:0};
}
