# Generated by Django 6.1 on 2026-09-15 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField(blank=True, default='', verbose_name='Lettre de motivation')),
                ('message_candidat', models.TextField(blank=True, default='', verbose_name='Message du candidat')),
                ('source', models.CharField(choices=[('PLATEFORME', 'Plateforme'), ('ALERTE', 'Alerte emploi'), ('RECOMMANDATION', 'Recommandation'), ('AUTRE', 'Autre')], default='PLATEFORME', max_length=30, verbose_name='Source')),
                ('statut', models.CharField(choices=[('RECUE', 'Candidature reçue'), ('PRESELECTION', 'Présélection'), ('ENTRETIEN', 'Entretien'), ('EVALUATION', 'Évaluation'), ('RETENU', 'Retenu'), ('REFUSE', 'Refusé'), ('RETIREE', 'Retirée')], default='RECUE', max_length=30, verbose_name='Statut')),
                ('statut_precedent', models.CharField(blank=True, choices=[('RECUE', 'Candidature reçue'), ('PRESELECTION', 'Présélection'), ('ENTRETIEN', 'Entretien'), ('EVALUATION', 'Évaluation'), ('RETENU', 'Retenu'), ('REFUSE', 'Refusé'), ('RETIREE', 'Retirée')], max_length=30, null=True, verbose_name='Statut précédent')),
                ('motif_refus', models.TextField(blank=True, default='', verbose_name='Motif du refus')),
                ('motif_retrait', models.TextField(blank=True, default='', verbose_name='Motif du retrait')),
                ('score_compatibilite', models.DecimalField(blank=True, decimal_places=2, help_text='Score ATS compris entre 0 et 100.', max_digits=5, null=True, verbose_name='Score de compatibilité')),
                ('analyse_ats', models.JSONField(blank=True, default=dict, help_text="Résultat détaillé de l'analyse ATS.", verbose_name='Analyse ATS')),
                ('score_ats_calcule', models.BooleanField(default=False, verbose_name='Score ATS calculé')),
                ('date_analyse_ats', models.DateTimeField(blank=True, null=True, verbose_name="Date d'analyse ATS")),
                ('note_interne', models.TextField(blank=True, default='', help_text='Note visible uniquement par le recruteur.', verbose_name='Note interne')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_preselection', models.DateTimeField(blank=True, null=True, verbose_name='Date de présélection')),
                ('date_entretien', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'entretien")),
                ('date_evaluation', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'évaluation")),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('date_retrait', models.DateTimeField(blank=True, null=True, verbose_name='Date de retrait')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(limit_choices_to={'role': 'CANDIDAT'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='users.cv', verbose_name='CV utilisé')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='offres.offre', verbose_name='Offre')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'db_table': 'candidatures',
                'ordering': ['-date_candidature'],
                'indexes': [models.Index(fields=['candidat', 'statut'], name='cand_candidat_statut_idx'), models.Index(fields=['offre', 'statut'], name='cand_offre_statut_idx'), models.Index(fields=['offre', '-date_candidature'], name='cand_offre_date_idx'), models.Index(fields=['score_compatibilite'], name='cand_score_ats_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidat', 'offre'), name='unique_candidature_candidat_offre')],
            },
        ),
    ]
