# Generated by Django 6.1 on 2026-09-12 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'offre")),
                ('reference', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Référence')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('missions', models.TextField(blank=True, verbose_name='Missions')),
                ('profil_recherche', models.TextField(blank=True, verbose_name='Profil recherché')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance')], max_length=20, verbose_name='Type de contrat')),
                ('niveau_experience', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('SENIOR', 'Senior'), ('EXPERT', 'Expert')], default='DEBUTANT', max_length=20, verbose_name="Niveau d'expérience")),
                ('experience_requise', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience requises")),
                ('niveau_etudes', models.CharField(choices=[('AUCUN', 'Aucun diplôme spécifique'), ('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire'), ('BAC', 'Baccalauréat'), ('BAC+2', 'Bac+2'), ('BAC+3', 'Bac+3 / Licence'), ('BAC+4', 'Bac+4'), ('BAC+5', 'Bac+5 / Master'), ('DOCTORAT', 'Doctorat')], default='AUCUN', max_length=20, verbose_name="Niveau d'études requis")),
                ('diplome_requis', models.CharField(blank=True, max_length=255, verbose_name='Diplôme requis')),
                ('competences', models.JSONField(blank=True, default=list, verbose_name='Compétences requises')),
                ('competences_validees', models.JSONField(blank=True, default=list, verbose_name='Compétences validées')),
                ('localisation', models.CharField(max_length=255, verbose_name='Localisation')),
                ('mode_travail', models.CharField(choices=[('SUR_SITE', 'Sur site'), ('HYBRIDE', 'Hybride'), ('DISTANCIEL', 'À distance')], default='SUR_SITE', max_length=20, verbose_name='Mode de travail')),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salaire minimum')),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salaire maximum')),
                ('devise', models.CharField(default='XAF', max_length=10, verbose_name='Devise')),
                ('salaire_confidentiel', models.BooleanField(default=False, verbose_name='Salaire confidentiel')),
                ('avantages', models.JSONField(blank=True, default=list, verbose_name='Avantages')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='offres/flyers/', verbose_name="Flyer de l'offre")),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_limite', models.DateField(verbose_name='Date limite de candidature')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('date_archivage', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de modération'), ('PUBLIEE', 'Publiée'), ('REJETEE', 'Rejetée'), ('SUSPENDUE', 'Suspendue'), ('EXPIREE', 'Expirée'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('moderation_status', models.CharField(choices=[('NON_SOUMISE', 'Non soumise'), ('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='NON_SOUMISE', max_length=20, verbose_name='Statut de modération')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('motif_suspension', models.TextField(blank=True, verbose_name='Motif de suspension')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('nombre_candidatures', models.PositiveIntegerField(default=0, verbose_name='Nombre de candidatures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='users.entreprise', verbose_name='Entreprise')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_recruteur', to=settings.AUTH_USER_MODEL, verbose_name='Recruteur')),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut'], name='offres_offr_statut_957e61_idx'), models.Index(fields=['type_contrat'], name='offres_offr_type_co_cb9f8c_idx'), models.Index(fields=['date_limite'], name='offres_offr_date_li_59ec95_idx'), models.Index(fields=['entreprise'], name='offres_offr_entrepr_faf5c8_idx'), models.Index(fields=['recruteur'], name='offres_offr_recrute_7552e9_idx'), models.Index(fields=['moderation_status'], name='offres_offr_moderat_d99e95_idx')],
            },
        ),
    ]
