# Generated by Django 6.1 on 2026-09-12 09:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('role', models.CharField(choices=[('CANDIDAT', 'Candidat'), ('RECRUTEUR', 'Recruteur'), ('ADMIN', 'Administrateur')], default='CANDIDAT', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Compte suspendu')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='Motif de suspension')),
                ('suspension_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de suspension')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_professionnel', models.CharField(blank=True, max_length=255, verbose_name='Titre professionnel')),
                ('bio', models.TextField(blank=True, verbose_name='Présentation')),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('disponibilite', models.CharField(blank=True, max_length=100, verbose_name='Disponibilité')),
                ('annees_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('competences', models.JSONField(blank=True, default=list, verbose_name='Compétences')),
                ('formations', models.JSONField(blank=True, default=list, verbose_name='Formations')),
                ('experiences', models.JSONField(blank=True, default=list, verbose_name='Expériences professionnelles')),
                ('langues', models.JSONField(blank=True, default=list, verbose_name='Langues')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_completion', models.PositiveIntegerField(default=0, verbose_name='Pourcentage de complétion')),
                ('is_profile_public', models.BooleanField(default=True, verbose_name='Profil public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_candidat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil candidat',
                'verbose_name_plural': 'Profils candidats',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'CV'), ('COVER_LETTER', 'Lettre de motivation'), ('PORTFOLIO', 'Portfolio'), ('CERTIFICATE', 'Certificat'), ('OTHER', 'Autre')], default='OTHER', max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.profilcandidat')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Mon CV', max_length=255)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Fichier CV')),
                ('contenu_en_ligne', models.JSONField(blank=True, default=dict, verbose_name='CV en ligne')),
                ('is_primary', models.BooleanField(default=False, verbose_name='CV principal')),
                ('is_generated', models.BooleanField(default=False, verbose_name='CV généré par HuntJobs')),
                ('template_name', models.CharField(blank=True, max_length=255, verbose_name='Template utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='users.profilcandidat')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
            },
        ),
        migrations.CreateModel(
            name='ProfilRecruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=255, verbose_name='Poste occupé')),
                ('telephone_professionnel', models.CharField(blank=True, max_length=30, verbose_name='Téléphone professionnel')),
                ('fonction', models.CharField(blank=True, max_length=255, verbose_name='Fonction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_recruteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil recruteur',
                'verbose_name_plural': 'Profils recruteurs',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'entreprise")),
                ('secteur_activite', models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité")),
                ('taille', models.CharField(blank=True, max_length=100, verbose_name="Taille de l'entreprise")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/', verbose_name='Logo')),
                ('email_professionnel', models.EmailField(blank=True, max_length=254, verbose_name='E-mail professionnel')),
                ('nui', models.CharField(blank=True, max_length=100, verbose_name="Numéro d'identifiant unique")),
                ('document_immatriculation', models.FileField(blank=True, null=True, upload_to='entreprises/verification/', verbose_name="Document d'immatriculation")),
                ('preuve_activite', models.FileField(blank=True, null=True, upload_to='entreprises/verification/', verbose_name="Preuve d'activité")),
                ('verification_status', models.CharField(choices=[('NOT_STARTED', 'Non commencée'), ('IN_PROGRESS', 'En cours'), ('PENDING', 'En attente de validation'), ('VERIFIED', 'Entreprise vérifiée'), ('REJECTED', 'Vérification refusée'), ('SUSPENDED', 'Entreprise suspendue')], default='NOT_STARTED', max_length=20, verbose_name='Statut de vérification')),
                ('verification_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de demande de vérification')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('verification_comment', models.TextField(blank=True, verbose_name='Commentaire de vérification')),
                ('email_professionnel_locked', models.BooleanField(default=False, verbose_name='E-mail professionnel verrouillé')),
                ('nui_locked', models.BooleanField(default=False, verbose_name='NUI verrouillé')),
                ('email_modification_allowed', models.BooleanField(default=False, verbose_name='Modification e-mail autorisée')),
                ('nui_modification_allowed', models.BooleanField(default=False, verbose_name='Modification NUI autorisée')),
                ('modification_request_reason', models.TextField(blank=True, verbose_name='Motif de demande de modification')),
                ('modification_request_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de demande de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Entreprise active')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Entreprise suspendue')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='Motif de suspension')),
                ('suspension_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profil_recruteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='users.profilrecruteur')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
    ]
