# Generated by Django 6.1 on 2026-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cv',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('candidat',), name='unique_primary_cv'),
        ),
    ]
